INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Shredded Lettuce', 7, 3, 0.25, '5 lb', 'base', 50, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Spinach', 6, 4, 0.25, '5 lb', 'base', 50, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Brown Rice', 3, 7, 0.25, '50 lb', 'base', 200, 30);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('White Rice', 3, 7, 0.25, '50 lb', 'base', 200, 30);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Chicken', 10, 0, 0.2, '160 oz', 'protein', 16, 100);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Lamb', 10, 0, 0.2, '160 oz', 'protein', 16, 290);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Falafel', 6, 4, 0.2, '160 oz', 'protein', 16, 100);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Beef', 3, 7, 0.2, '160 oz', 'protein', 16, 290);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Pork', 4, 6, 0.2, '160 oz', 'protein', 16, 290);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Couscous', 4, 6, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Onions', 4, 6, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Big Tomatoes', 10, 0, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Small Tomatoes', 3, 7, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Pita Chips', 4, 6, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Vegetable Medley', 9, 1, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Olives', 10, 0, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Pickled Onions', 2, 8, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Cucumbers', 2, 8, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Cauliflower', 2, 8, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Peppers', 8, 2, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Red Cabbage Coleslaw', 8, 2, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Garlic Fries', 10, 0, 0.13333333333333333, '80 oz', 'toppings', 20, 40);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Hummus', 3, 7, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Spicy Hummus', 10, 0, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Jalapeno Feta', 2, 8, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Tzatziki', 7, 3, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Greek Vinaigrette', 5, 5, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Harrisa Yogurt', 8, 2, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Dill Yogurt', 2, 8, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Tahini', 7, 3, 0.1111111111111111, '16 oz', 'sauces', 16, 25);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Pepsi', 5, 5, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Sierra Mist', 6, 4, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Brisk', 7, 3, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Pepsi Zero', 7, 3, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Diet Pepsi', 7, 3, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Gatorade', 5, 5, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Mtn Dew', 6, 4, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Dr. Pepper', 8, 2, 0.1, '5 gallon', 'drinks', 100, 50);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Cup Drink', 10, 0, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Cup Water', 10, 0, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Bowl', 2, 8, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Straw', 9, 1, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Cup Lid', 9, 1, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Bowl Lid', 2, 8, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
INSERT INTO "InventoryItems" ("Name", "Stock", "NumberNeeded", "OrderChance", "Units", "Category", "Servings", "RestockCost") VALUES ('Utensil Pack', 2, 8, 0.5, '500 count boxes', 'nonPerishable', 500, 20);
